Broke AF (#1)
* JSON Deserialization broke

System.Text.Json.JsonException: 'The JSON value could not be converted to System.Collections.Generic.List`1[iprep.AIPDB_Check_Root]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.'

* Update iprep.cs

Stupidly burned an API key

* Returns json string

bypassed json deserialization for now, at least getting the information desired from abuseipdb.

* DataContractJsonSerialize

Trying a different approach.

* Working!

successfully deserializes the json object and creates object structure to access data