JSON Deserialization broke
System.Text.Json.JsonException: 'The JSON value could not be converted to System.Collections.Generic.List`1[iprep.AIPDB_Check_Root]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.'